### ISSUE TITLE
print() replaces a global function in some framework environment

### ISSUE THREAD

**Issue by XtremePlayzCODE** [TinyDev/Log.js#1]
Some frameworks compatible with Node use the `print` function and so this overrides it.

And also why are you in my Angled repo?

**Comment by FantasyIsBae** [comment]
Thanks and Idk I like the idea :P

**Comment by FantasyIsBae** [comment]
And also if you have any ideas , etc 
Im on skype most of the time so call me or text me there 👍 
SKYPE: FantasyIsBae

**Comment by XtremePlayzCODE** [comment]
I really need help on Angled and was wondering if you would join, I'll text you on skype

**Comment by XtremePlayzCODE** [comment]
Resolved?

**Comment by FantasyIsBae** [comment]
Sheet no i closed it accidentally

**Comment by XtremePlayzCODE** [comment]
K, this can be easily fixed too

**Comment by FantasyIsBae** [comment]
Can u do it , i don't have too much time , sorry

**Comment by XtremePlayzCODE** [comment]
Fixed in PR

**Comment by FantasyIsBae** [comment]
Thanks and also i have added u to the org :)

**Comment by XtremePlayzCODE** [comment]
K, I'll make some shit
